version: "3.8"

services:
  configserver:
    image: vjloable/configserver:latest
    ports:
      - "8071:8071"
    networks:
      - vjloable-network

  discoveryserver:
    image: vjloable/discoveryserver:latest
    ports:
      - "8070:8070"
    networks:
      - vjloable-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071

  accounts:
    image: vjloable/accounts:latest
    ports:
      - "8080:8080"
    networks:
      - vjloable-network
    depends_on:
      - configserver
      - discoveryserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryserver:8070/eureka/

  loans:
    image: vjloable/loans:latest
    ports:
      - "8090:8090"
    networks:
      - vjloable-network
    depends_on:
      - configserver
      - discoveryserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryserver:8070/eureka/

  cards:
    image: vjloable/cards:latest
    ports:
      - "9000:9000"
    networks:
      - vjloable-network
    depends_on:
      - configserver
      - discoveryserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryserver:8070/eureka/
      
networks:
  vjloable-network: